#
# docker-compose.yml — определяет сервисы для разработки и тестирования.

#Что нужно сделать:
#  - Настроить сервисы для:
#      - PostgreSQL (или MySQL) с начальной базой.
#      - Приложения Spring Boot (если нужно).
#  - Открыть нужные порты (например, 5432, 8080).
#  - Настроить volume для хранения данных БД.

version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bank_cards_postgres
    environment:
      POSTGRES_DB: bank_cards_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: darina2003z1x2c3
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  bank-cards-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank_cards_app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bank_cards_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: darina2003z1x2c3
    volumes:
      - ./migration:/app/migration

volumes:
  postgres_data: